HARD_SHELL_DIFF = 4
MIN_HUNGRY_SPECIES = 2

CARNIVORE = "carnivore"
AMBUSH = "ambush"
BURROWING = "burrowing"
CLIMBING = "climbing"
COOPERATION = "cooperation"
FATTISSUE = "fat-tissue"
FERTILE = "fertile"
FORAGING = "foraging"
HARDSHELL = "hard-shell"
HERDING = "herding"
HORNS = "horns"
LONGNECK = "long-neck"
PACKHUNTING = "pack-hunting"
SCAVENGER = "scavenger"
SYMBIOSIS = "symbiosis"
WARNINGCALL = "warning-call"

ID = "id"
SPECIES = "species"
BAG = "bag"
FOOD = "food"
BODY = "body"
POPULATION = "population"
TRAITS = "traits"
FATFOOD = "fat-food"
CARDS = "cards"

MIN_WATERING_HOLE = 0
CONFIG_LENGTH = 3
LOP_MIN = 3
LOP_MAX = 8
LOC_MAX = 122
FEEDING_LENGTH = 3
WH_FEEDING_INDEX = 1
PLAYER_FEEDING_INDEX = 0
LOP_FEEDING_INDEX = 2
PLAYER_LENGTH = 3
PLAYER_PLUS_LENGTH = 4
PLAYER_FOOD_BAG_INDEX = 2
PLAYER_ID_INDEX = 0
MAX_TRAITS = 3
MIN_FOOD_BAG = 0
MIN_FOOD = 0
MAX_FOOD = 7
MIN_POP = 1
MAX_POP = 7
MIN_BODY = 0
MAX_BODY = 7
MIN_FATFOOD = 0
MIN_PLAYER_ID = 1
SPECIES_FAT_LENGTH = 5
SPECIES_LENGTH = 4
SPECIES_CARD_LENGTH = 2
CARN_FOOD_MIN = -8
CARN_FOOD_MAX = 8
HERB_FOOD_MIN = -3
HERB_FOOD_MAX = 3


TRAITS_LIST = [CARNIVORE, AMBUSH, BURROWING, CLIMBING, COOPERATION, FATTISSUE, FERTILE, FORAGING,
               HARDSHELL, HERDING, HORNS, LONGNECK, PACKHUNTING, SCAVENGER, SYMBIOSIS,  WARNINGCALL]