#! /usr/bin/env python

"""
A test harness for the Dealer feed1 method
"""

import json
import sys

from convert import Convert


def main():
    json_config = json.loads(sys.stdin.read())
    try:
        dealer = Convert.json_to_dealer(json_config)
        dealer.validate()
        dealer.feed1(dealer.list_of_players[0])
        json_dealer = Convert.dealer_to_json(dealer)
        sys.stdout.write(json.dumps(json_dealer))
    except Exception as exc:
        print exc
        sys.exit(0)


if __name__ == "__main__":
    main()