#! /usr/bin/env python

import socket
from dealer.player import Player
from dealer_proxy import Dealer_Proxy
from convert import *
from dealer.globals import *


def main():
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.connect((HOSTNAME, PORT))
    try:
        sock.sendall(json.dumps(SIGNUP_MSG))
        response = Convert.listen(sock)
        if response == SIGNUP_RSP:
            dealer_proxy = Dealer_Proxy(Player(), sock)
            dealer_proxy.wait_for_start()
    finally:
        sock.close()


if __name__ == "__main__":
    main()
