#! /usr/bin/env python

import sys
import socket
from dealer.player import Player
from dealer_proxy import Dealer_Proxy
from convert import *
from dealer.globals import *


def main(username, hostname, port):
    """
    Connects this client to a TCP server and creates a Dealer Proxy
    :param username: String identifying this client
    :param hostname: String representing the TCP server hostname
    :param port: String representing the TCP server port
    :effect: Creates a Dealer Proxy which waits for the server to start the game
    """
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.connect((hostname, int(port)))
    try:
        sock.sendall(json.dumps(username))
        response = Convert.listen(sock)
        if response == SIGNUP_RSP:
            dealer_proxy = Dealer_Proxy(Player(), sock)
            dealer_proxy.wait_for_start()
    finally:
        sock.close()


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2], sys.argv[3])
